import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import { AppHeader } from "@/components/layout/app-header";
import { AppSidebar } from "@/components/layout/app-sidebar";

const _inter = Inter({ subsets: ["latin"] })
const _poppins = Poppins({ subsets: ["latin"], weight: ["400", "500", "600", "700"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return <html lang="en">
    <body className={`${_inter.className} font-sans antialiased min-h-screen h-max w-full px-6 py-3`}
      style={{
        backgroundImage: "url(/bg.svg)", backgroundSize: "cover"
      }}>
      <div className="flex flex-row h-full w-full gap-6">
        <AppSidebar />
        <div className="flex-1 flex flex-col ml-4">
          <AppHeader />
          <main className="flex-1 mt-4">
            {children}
          </main>
        </div>
      </div>

    </body>
  </html>





}


/*  don't remove this
 return (
    <html lang="en">
      <body className={`${_inter.className} font-sans antialiased min-h-screen h-max w-full px-6 py-3`}
        style={{
          backgroundImage: "url(/bg.svg)"
        }}>
        <div className="flex flex-row h-full w-full gap-6">
          <AppSidebar />
          <div className="flex-1 flex flex-col ml-4">
            <AppHeader />
            <main className="flex-1 mt-4">
              {children}
            </main>
          </div>
        </div>

      </body>
    </html>
  );
*/